name: flowers102_env
channels:
  - defaults
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pytorch=1.8.0
  - torchvision=0.9.0
  - cudatoolkit=11.1
  - matplotlib=3.4.2
  - numpy=1.20.2
  - pillow=8.2.0